name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to S3
        run: |
          aws s3 sync ./.https://github.com/NahomNG/Test-knowit s3://knowittest-20230914
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETACCESS }}
