name: Push to AWS S3

 

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger this on

 

jobs:
  deploy:
    runs-on: ubuntu-latest

 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

 

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

 

    - name: Install AWS CLI
      run: |
        pip install awscli
      env:
        AWS_DEFAULT_REGION: us-east-1  # Change this to your AWS region

 

    - name: Configure AWS Credentials
      run: |
        aws configure set accesskey AKIA34SNR4GUFUNY4AE2
        aws configure set secretaccess RfurH+yP/BAcgWoLU7ZjPkmY33n8O927GZIfU4LG
      env:
        AWS_DEFAULT_REGION: us-east-1  # Change this to your AWS region

 

    - name: Sync Files to S3 Bucket
      run: |
        aws s3 cp ./index.html s3://knowittest-20230914/
        aws s3 cp ./game.js s3://knowittest-20230914/
      working-directory: ./
